version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.10.0
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: npm install
      - run:
          name: run test
          command: npm run build

workflows:
   build_deploy:
        jobs:
         - build
